### ISSUE TITLE
部分模块不含样式，插件会自动索引样式文件导致报错

### ISSUE THREAD

**Issue by tomoyuen** [QingWei-Li/babel-plugin-component#1]
在使用vux时，自定义了libDir，能够简洁方便低导入需要的组件，但是对于vux的子组件，由于编译产出的dist目录里对应的子组件不含css样式文件，导致node导入模块失败。
请问能不能做到遍历对应模块目录，根据是否包含样式文件，再导入样式模块呢？

**Comment by QingWei-Li** [comment]
Hi
这个问题我以前考虑过：
1. 我不确定在 babel 插件进行文件操作是否合理。之前确实是有考虑过判断文件存不存在再导入文件, 但是我查了下 babel 官方的插件没有一个调用了 fs 模块。而且我觉得进行文件操作或多或少会影响执行效率。
2. 我觉得组件的目录结构应该统一。即使没有样式文件，也应该创建一个空内容的样式文件，确保所有场景下使用行为一致（用户也不知道到底哪些组件有样式哪些没有，如果有的组件没有样式文件却误认为有文件并引入，结果报错，开发体验不够友好）。空文件也并不影响最后打包结果。

``` json
- component
 - index.js
 - style.css
```

所以解决方法，如果说 babel-plugin-component 能和 vux 兼容的话，应该找 vux 的作者商量下，仿照 mint-ui 那样即使不需要样式文件的组件也打包一份空的样式文件。你觉得呢？

**Comment by tomoyuen** [comment]
嗯，在我发issue之前，我就在想到底该发到这，还是vux呢。我也比较偏向于组件输出同样的目录结构，随后又考虑到插件的容错性等等，不过从执行效率和处理成本来看，输出一致的目录结构都是一个不错的方案。

**Comment by airyland** [comment]
放一个空的样式文件可以做

感觉检查样式文件是否存在其实也可以优化一下，对特定版本的模块只检查一次就行了，写入配置，下次只需要读配置就行了。

其实vux更推荐从src目录引入.vue组件，但是同样会有目录问题，像Tabbar, TabbarItem 入口是 `/components/tabbar/index.js`  但是这个似乎不好从插件上解决。。

**Comment by QingWei-Li** [comment]
@airyland @tomoyuen  Hi 

出发点不同吧。我们更推荐用户使用编译过后的文件，所以才会要求组件的文件目录结构(dist)一致。使用编译过的文件有以下考虑:
1. 编译文件是有成本的
2. 用户的配置不一定就能满足我们需要的配置，那么就必须强制用户使用同样的配置（可能这套配置只是为了满足这套组件库）；同时也限制了开发者以后的扩展

至于检测文件是否存在这件事，我还是认为不应该让 babel 插件来做，毕竟 babel 只是一个编译器(compiler)。

**Comment by tomoyuen** [comment]
单从使用者的角度看，我也觉得使用编译后的文件更好一点^_^。

**Comment by seafronthu** [comment]
可还是架不住调用了
![Uploading image.png…]()

**Comment by seafronthu** [comment]
可还是架不住调用了
![image](https://user-images.githubusercontent.com/50374650/210543361-38161bf6-508d-4376-ae28-24b58545905d.png)
