### ISSUE TITLE
Nuxt.js中引入按需加载element-ui组件报错

### ISSUE THREAD

**Issue by ChiaJune** [QingWei-Li/babel-plugin-component#13]
### ElementUI version
v1.2.7
### babel-plugin-component version
v0.9.1
### OS/Browers version
Win7/Chrome57.0.2987.133
### Vue version
v2.2.6
### Nuxt configuration
`nuxt.config.js`
``` javascript
// ...
babel: {
  plugins: ['transform-async-to-generator', 'transform-runtime', ['component', [{
    libraryName: 'element-ui',
    styleLibraryName: 'theme-default'
  }]]]
}
// ...
``` 
### What is actually happening?
``` bash
 error  in ./~/element-ui/lib/theme-default/date-picker.css

Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../css-loader/index.js!./date-picker.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../../vue-style-loader/lib/addStylesClient.js")("1bb6a9ee", content, false);


 @ ./~/element-ui/lib/theme-default/date-picker.css 4:14-137 13:3-17:5 14:22-145
 @ ./~/babel-loader/lib?{"plugins":["transform-async-to-generator","transform-runtime",["component",[{"libraryName":"element-ui","styleLibraryName":"theme-default"}]]],"presets":["vue-app"],
"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

 error  in ./~/element-ui/lib/theme-default/base.css

Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../css-loader/index.js!./base.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../../vue-style-loader/lib/addStylesClient.js")("7011cd8e", content, false);


 @ ./~/element-ui/lib/theme-default/base.css 4:14-130 13:3-17:5 14:22-138
 @ ./~/babel-loader/lib?{"plugins":["transform-async-to-generator","transform-runtime",["component",[{"libraryName":"element-ui","styleLibraryName":"theme-default"}]]],"presets":["vue-app"],
"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js
```

麻烦您帮我看看是不是哪里配置错了？

**Comment by ChiaJune** [comment]
#### 补充
如果不使用`styleLibraryName: 'theme-default'`就好了

``` javascript
// ...
css: ['element-ui/lib/theme-default/index.css'],
build: {
  babel: {
    plugins: ['transform-async-to-generator', 'transform-runtime', ['component', [{
      libraryName: 'element-ui'
      // styleLibraryName: 'theme-default'
    }]]]
  },
  // ...
}
// ...
```

**Comment by QingWei-Li** [comment]
nuxt.js 不支持 import css（吧？）

**Comment by lincenying** [comment]
https://github.com/lincenying/nuxt-demo/blob/master/.babelrc#L9-L12

没有问题

**Comment by fxh615** [comment]
i have the same problem 

 3 | // load the styles
  4 | var content = require("!!../../../.0.28.0@css-loader/index.js!./step.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // add the styles to the DOM
  7 | var update = require("!../../../.0.14.1@style-loader/addStyles.js")(content, {});
  8 | if(content.locals) module.exports = content.locals;


 @ ./~/.1.2.9@element-ui/lib/theme-default/step.css 4:14-150 13:3-17:5 14:22-158
 @ ./~/.6.4.1@babel-loader/lib?{"presets":["es2015","stage-2"],"plugins":[["transform-vue-jsx"],"transform-export-extensions",["transform-runtime",{"polyfill":true,"regenerator":true}],["component",[{"libraryName":"element-ui","styleLibraryName":"theme-default"}]]],"comments":false,"babelrc":false,"cacheDirectory":true}!./~/.11.3.4@vue-loader/lib/selector.js?type=script&index=0!./pages/create/index.vue
 @ ./pages/create/index.vue

**Comment by zhch0633** [comment]
I have the same problem and found a correct solution here 
[https://github.com/ElemeFE/element/issues/478](https://github.com/ElemeFE/element/issues/478)

``````
build: {
    loaders: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader', 'postcss-loader']
      },
      {
        test: /\.(png|jpg|jpeg|gif|eot|ttf|woff|woff2|svg|svgz)(\?.+)?$/,
        use: [{
          loader: 'url-loader',
          options: {
            limit: 10000
          }
        }]
      }
    ]
  }
``````

 change default loader to a traditional one

**Comment by sunlanda** [comment]
1.  nuxt.conf.js  中plugins写入 [{
    src: '~plugins/element-ui',
    ssr: true
  }]

2. plugins文件夹下新建element-ui.js  
写入
import Vue from 'vue'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-default/index.css'
Vue.use(ElementUI)

3. npm run dev // 组件以及样式都可以生效了
