### ISSUE TITLE
Question : Can I change CSS colors dynamically?

### ISSUE THREAD

**Issue by XavRsl** [QingWei-Li/babel-plugin-component#26]
Hi,

My client is asking me to allow users to create their own Blog-like pages on our platform. These blogs should all look different, and one of the demands is to allow users to change the colors of the elements on the page (buttons, text, header, ...). Could it be possible to load the styles but change the colors according to the color selected by the user when using babel-plugin-component?

Thanks.

Xavier

**Comment by QingWei-Li** [comment]
This plugin can only help you to modify the theme variables during development. Perhaps you can refer to https://elementui.github.io/theme-preview/#/en-US

**Comment by XavRsl** [comment]
Thanks, OK, that's what I thought. I saw the theme preview but seemed to be a bit too complicated just to change colors on the fly.

Thanks.
