### ISSUE TITLE
import { DatePicker } from 'element-ui' ，但没有import date-picker 样式文件，样式出不来

### ISSUE THREAD

**Issue by qiulang** [QingWei-Li/babel-plugin-component#29]
已经配置好 babel-plugin-component, build后 js文件从 936KB缩小到 367KB。但是样式文件没有缩小。
我想是因为我的代码把样式全部引入 import 'element-ui/lib/theme-chalk/index.css'
把这句去掉又会没有样式，可是README不是说了

Converts

import { Button } from 'components'
to

var button = require('components/lib/button')
require('components/lib/button/style.css')

那按说不需要再引入样式了啊 ？
请问到底要如何 按需引入组件的样式文件 ？

**Comment by yiwuyu** [comment]
@qiulang 请问这个问题解决了吗
