### ISSUE TITLE
If you are using bothon-demand and importing all, make sure to invoke the importing all first

### ISSUE THREAD

**Issue by xcsweb** [QingWei-Li/babel-plugin-component#62]
![](https://user-gold-cdn.xitu.io/2020/6/3/1727956d7e77d96b?w=949&h=490&f=png&s=35483)

![](https://user-gold-cdn.xitu.io/2020/6/3/1727957830777714?w=895&h=677&f=png&s=61053)

![](https://user-gold-cdn.xitu.io/2020/6/3/1727957c4e1f521a?w=937&h=192&f=png&s=29166)
我按需重写了element-input ，element.js的顺序的引入顺序也是对的，不知道为啥报这个错

**Comment by xcsweb** [comment]
我把ElementUI里面我用不到的全部都排除了，重新注册的,再把新的input覆盖原来的element-input

**Comment by xcsweb** [comment]
https://pic4.zhimg.com/80/v2-7c2b496e2220334b95c75baa404da5c2_720w.png
，查出来了,element-ui@2.4.1 跟element-ui@2.13.1 element-ui.d.ts ，
https://pic3.zhimg.com/80/v2-4e30e528d18f93ae0af82992d9fb42e4_720w.png
，因为我有babel-plugin-component，导致
https://pic1.zhimg.com/80/v2-391550ac6b7ff919b17ba65bf42c9db6_720w.png
https://pic2.zhimg.com/80/v2-30fe989eb1758677e7923e7aabe3a658_720w.png
https://pic1.zhimg.com/80/v2-ece7017f05d93325d82a8b2f53159dd1_720w.png
我的使用和官网提示的区别不大

**Comment by Liubasara** [comment]
> https://pic4.zhimg.com/80/v2-7c2b496e2220334b95c75baa404da5c2_720w.png ，查出来了,element-ui@2.4.1 跟element-ui@2.13.1 element-ui.d.ts ， https://pic3.zhimg.com/80/v2-4e30e528d18f93ae0af82992d9fb42e4_720w.png ，因为我有babel-plugin-component，导致 https://pic1.zhimg.com/80/v2-391550ac6b7ff919b17ba65bf42c9db6_720w.png https://pic2.zhimg.com/80/v2-30fe989eb1758677e7923e7aabe3a658_720w.png https://pic1.zhimg.com/80/v2-ece7017f05d93325d82a8b2f53159dd1_720w.png 我的使用和官网提示的区别不大

我这边也遇到了相同的问题，请问大佬是如何解决的？

**Comment by chenkitchen** [comment]
全局注册的element，改成按需引用
