### ISSUE TITLE
在laravel里的elixir怎么配置？

### ISSUE THREAD

**Issue by woodytang** [QingWei-Li/babel-plugin-component#7]
`    Elixir.webpack.mergeConfig({
        resolveLoader: {
            root: path.join(__dirname, 'node_modules'),
        },
        babel: {
            presets: ["es2015", {
                "modules": false
            }],
            plugins: ["component", [{
                "libraryName": "element-ui",
                "styleLibraryName": "theme-default"
            }]]

        },
        module: {
            loaders: [{
                test: /\.css$/,
                loader: 'style!css'
            }]
        }
        

    });`
我这样配置没用，压出来还是一样大

**Comment by QingWei-Li** [comment]
看起来配置没错，请给一个 repo 地址
